name: vscode extension
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      # fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: "*"

      - name: linux Install dosbox and dosbox-x tool
        run: |
          sudo apt-get update
          sudo apt-get install dosbox
          sudo apt install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install flathub com.dosbox_x.DOSBox-X -y
        if: runner.os == 'Linux'
      - name: macOS Install dosbox and dosbox-x tool
        run: |
          brew update
          brew install dosbox
          brew install dosbox-x
        if: runner.os == 'macOS'

      - name: start xvfb for linux
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: runner.os == 'Linux'

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: install and test vscode-dosbox
        run: |
          pnpm install
          pnpm compile
          pnpm test
          pnpm test-local
        working-directory: ./vscode-dosbox
        env:
          DISPLAY: ":99.0"

      - name: package
        run: node dev/package.js
        working-directory: ./vscode-dosbox

      - name: install and test ./masm-tasm
        run: |
          yarn
          yarn test && yarn test-web
        working-directory: ./masm-tasm
        env:
          DISPLAY: ":99.0"

      - run: yarn lint
        if: runner.os == 'Linux'

  build:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
  
      - name: install and package vscode-dosbox
        working-directory: ./vscode-dosbox
        run: |
          yarn
          node dev/package.js --all
      - uses: actions/upload-artifact@v2
        with:
          name: "vscepackages"
          path: "./vscode-dosbox/*.vsix"

      - run: npx vsce publish --packagePath $(find . -iname "*.vsix")
        working-directory: ./vscode-dosbox
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        if: success() && startsWith( github.ref, 'refs/tags/')

      - name: Publish
        if: success() && startsWith( github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: npx vsce publish  --yarn
        working-directory: ./masm-tasm
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
